# Generated by Django 6.0.4 on 2026-04-29 00:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilAdministrativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo')),
                ('setor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Setor')),
                ('ativo', models.BooleanField(default=True, verbose_name='Administrador ativo')),
                ('data_promocao', models.DateTimeField(auto_now_add=True, verbose_name='Data de promoção')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações internas')),
                ('promovido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admins_promovidos', to=settings.AUTH_USER_MODEL, verbose_name='Promovido por')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_administrativo', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Perfil Administrativo',
                'verbose_name_plural': 'Perfis Administrativos',
                'permissions': [('pode_validar_denuncia', 'Pode validar denúncia'), ('pode_publicar_denuncia', 'Pode publicar denúncia'), ('pode_promover_usuario', 'Pode promover usuário'), ('pode_rebaixar_admin', 'Pode rebaixar admin'), ('pode_alterar_permissionamento', 'Pode alterar permissionamento')],
            },
        ),
    ]
