# Generated by Django 6.0.4 on 2026-06-19 22:04

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gerenciamento", "0002_passwordresettoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="telefone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None
            ),
        ),
    ]
