# Generated by Codex on 2026-06-06.

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DocumentoTransparencia",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("titulo", models.CharField(max_length=200)),
                ("descricao", models.TextField(blank=True, default="")),
                ("arquivo_pdf", models.FileField(upload_to="transparencia/%Y/%m/%d")),
                ("ano", models.PositiveIntegerField(db_index=True)),
                ("categoria", models.CharField(choices=[("balancete", "Balancete"), ("ata", "Ata"), ("relatorio", "Relatorio"), ("outro", "Outro")], db_index=True, max_length=20)),
                ("ativo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Documento de transparência",
                "verbose_name_plural": "Documentos de transparência",
                "ordering": ["-ano", "-created_at", "-id"],
            },
        ),
    ]
