<<<<<<< HEAD
# Generated by Codex on 2026-06-06.

from django.db import migrations, models
=======
from django.db import migrations, models
import django.db.models.deletion
>>>>>>> 66bd021687c997b8237d20f869b787936f153549


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name="DocumentoTransparencia",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("titulo", models.CharField(max_length=200)),
                ("descricao", models.TextField(blank=True, default="")),
                ("arquivo_pdf", models.FileField(upload_to="transparencia/%Y/%m/%d")),
                ("ano", models.PositiveIntegerField(db_index=True)),
                ("categoria", models.CharField(choices=[("balancete", "Balancete"), ("ata", "Ata"), ("relatorio", "Relatorio"), ("outro", "Outro")], db_index=True, max_length=20)),
=======
            name="Categoria",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=100)),
                ("tipo", models.CharField(choices=[("entrada", "Entrada"), ("saida", "Saída")], db_index=True, max_length=10)),
>>>>>>> 66bd021687c997b8237d20f869b787936f153549
                ("ativo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
<<<<<<< HEAD
                "verbose_name": "Documento de transparência",
                "verbose_name_plural": "Documentos de transparência",
                "ordering": ["-ano", "-created_at", "-id"],
=======
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorias",
                "ordering": ["tipo", "nome"],
            },
        ),
        migrations.CreateModel(
            name="Movimento",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("descricao", models.CharField(max_length=300)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("data", models.DateField()),
                ("comprovante", models.FileField(blank=True, null=True, upload_to="transparencia/%Y/%m/%d")),
                ("ativo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("categoria", models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name="movimentos",
                    to="transparencia.categoria",
                )),
            ],
            options={
                "verbose_name": "Movimento",
                "verbose_name_plural": "Movimentos",
                "ordering": ["-data", "-created_at"],
>>>>>>> 66bd021687c997b8237d20f869b787936f153549
            },
        ),
    ]
