# Generated by Django 6.0.4 on 2026-06-13 01:03

import core.uploads
import core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("entrada", "Entrada"), ("saida", "Saída")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorias",
                "ordering": ["tipo", "nome"],
            },
        ),
        migrations.CreateModel(
            name="DocumentoInstitucional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("descricao", models.CharField(blank=True, default="", max_length=300)),
                (
                    "arquivo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=core.uploads.upload_transparencia_documentos,
                        validators=[core.validators.validate_document_upload],
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                ("ordem", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Documento Institucional",
                "verbose_name_plural": "Documentos Institucionais",
                "ordering": ["ordem", "nome"],
            },
        ),
        migrations.CreateModel(
            name="Indicador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chave",
                    models.CharField(
                        choices=[
                            ("animais_resgatados", "Animais resgatados"),
                            ("castracoes", "Castrações realizadas"),
                            ("adocoes", "Adoções bem-sucedidas"),
                        ],
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("valor", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Indicador de impacto",
                "verbose_name_plural": "Indicadores de impacto",
                "ordering": ["chave"],
            },
        ),
        migrations.CreateModel(
            name="Movimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(max_length=300)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("data", models.DateField()),
                (
                    "comprovante",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=core.uploads.upload_transparencia,
                        validators=[core.validators.validate_document_upload],
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimentos",
                        to="transparencia.categoria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimento",
                "verbose_name_plural": "Movimentos",
                "ordering": ["-data", "-created_at"],
            },
        ),
    ]
