# Generated by Django 6.0.4 on 2026-06-25 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transparencia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimento',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Movimento',
        ),
    ]
