# Generated by Django 6.0.4 on 2026-06-07 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transparencia", "0002_documentoinstitucional"),
    ]

    operations = [
        migrations.CreateModel(
            name="Indicador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chave",
                    models.CharField(
                        choices=[
                            ("animais_resgatados", "Animais resgatados"),
                            ("castracoes", "Castrações realizadas"),
                            ("adocoes", "Adoções bem-sucedidas"),
                        ],
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("valor", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Indicador de impacto",
                "verbose_name_plural": "Indicadores de impacto",
                "ordering": ["chave"],
            },
        ),
    ]
