# Generated by Django 6.0.4 on 2026-06-11 21:52

import core.uploads
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transparencia", "0003_indicador"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentoinstitucional",
            name="arquivo",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=core.uploads.upload_transparencia_documentos,
                validators=[core.validators.validate_document_upload],
            ),
        ),
        migrations.AlterField(
            model_name="movimento",
            name="comprovante",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=core.uploads.upload_transparencia,
                validators=[core.validators.validate_document_upload],
            ),
        ),
    ]
