# Generated by Django 6.0.4 on 2026-08-18 23:35

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PedidoCastracao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Nome da pessoa responsável pelo animal",
                        max_length=200,
                    ),
                ),
                (
                    "telefone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        help_text="Telefone para contato", max_length=128, region=None
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Email para contato (opcional)",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "tipo_animal",
                    models.CharField(
                        choices=[
                            ("cachorro", "Cachorro"),
                            ("gato", "Gato"),
                            ("outros", "Outros"),
                        ],
                        help_text="Tipo do animal: cachorro, gato ou outros",
                        max_length=20,
                    ),
                ),
                (
                    "sexo",
                    models.CharField(
                        choices=[("macho", "Macho"), ("femea", "Fêmea")],
                        help_text="Sexo do animal",
                        max_length=10,
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(
                        blank=True,
                        help_text="Informações adicionais sobre o animal (opcional)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("agendada", "Agendada"),
                            ("realizada", "Realizada"),
                        ],
                        default="pendente",
                        help_text="Andamento do pedido de castração",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Pedido de castração",
                "verbose_name_plural": "Pedidos de castração",
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
