# Generated by Django 6.0.4 on 2026-08-23 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('castracao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedidocastracao',
            options={'ordering': ['created_at', 'id'], 'verbose_name': 'Pedido de castração', 'verbose_name_plural': 'Pedidos de castração'},
        ),
    ]
