# Generated by Django 6.0.4 on 2026-06-13 01:03

import core.uploads
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DadosPix",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chave_pix",
                    models.CharField(
                        help_text="Chave Pix (CPF, CNPJ, email, telefone ou chave aleatoria)",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "qr_code",
                    models.ImageField(
                        blank=True,
                        help_text="Imagem do QR Code para leitura",
                        null=True,
                        upload_to=core.uploads.upload_qr_codes,
                        validators=[core.validators.validate_image_upload],
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        blank=True,
                        help_text="Descricao opcional sobre a doacao",
                        null=True,
                    ),
                ),
                (
                    "banco",
                    models.CharField(
                        blank=True,
                        help_text="Nome do banco para transferencia",
                        max_length=80,
                        null=True,
                    ),
                ),
                (
                    "agencia",
                    models.CharField(
                        blank=True,
                        help_text="Agencia bancaria",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "conta",
                    models.CharField(
                        blank=True, help_text="Conta bancaria", max_length=30, null=True
                    ),
                ),
                (
                    "tipo_conta",
                    models.CharField(
                        blank=True, help_text="Tipo de conta", max_length=40, null=True
                    ),
                ),
                (
                    "cnpj",
                    models.CharField(
                        blank=True,
                        help_text="CNPJ do favorecido",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "favorecido",
                    models.CharField(
                        blank=True,
                        help_text="Nome do favorecido",
                        max_length=120,
                        null=True,
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        default=True,
                        help_text="Define se este dado de doacao esta ativo",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Dados Pix",
                "verbose_name_plural": "Dados Pix",
            },
        ),
    ]
