# Generated by Django 6.0.4 on 2026-06-07 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DadosPix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave_pix', models.CharField(help_text='Chave Pix (CPF, CNPJ, email, telefone ou chave aleatória)', max_length=255, unique=True)),
                ('qr_code', models.ImageField(help_text='Imagem do QR Code para leitura', upload_to='qr_codes/')),
                ('descricao', models.TextField(blank=True, help_text='Descrição opcional sobre a doação', null=True)),
                ('ativo', models.BooleanField(default=True, help_text='Define se este dado de Pix está ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dados Pix',
                'verbose_name_plural': 'Dados Pix',
            },
        ),
    ]
