# Generated by Django 6.0.4 on 2026-05-28 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doacoes", "0002_dadospix_banco_agencia_conta_tipo_conta_cnpj_favorecido"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dadospix",
            name="ativo",
            field=models.BooleanField(
                default=True, help_text="Define se este dado de doacao esta ativo"
            ),
        ),
        migrations.AlterField(
            model_name="dadospix",
            name="chave_pix",
            field=models.CharField(
                help_text="Chave Pix (CPF, CNPJ, email, telefone ou chave aleatoria)",
                max_length=255,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="dadospix",
            name="descricao",
            field=models.TextField(
                blank=True, help_text="Descricao opcional sobre a doacao", null=True
            ),
        ),
    ]
