# Generated by Django 6.0.4 on 2026-06-11 21:52

import core.uploads
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doacoes", "0004_alter_dadospix_qr_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dadospix",
            name="qr_code",
            field=models.ImageField(
                blank=True,
                help_text="Imagem do QR Code para leitura",
                null=True,
                upload_to=core.uploads.upload_qr_codes,
                validators=[core.validators.validate_image_upload],
            ),
        ),
    ]
