# Generated by Django 6.0.4 on 2026-06-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doacoes", "0004_alter_dadospix_qr_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="DoacaoItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(help_text="Nome do doador", max_length=100)),
                (
                    "telefone",
                    models.CharField(help_text="Telefone de contato", max_length=20),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="E-mail de contato (opcional)",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        help_text="Descrição do item ou serviço a ser doado",
                        max_length=1000,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Doação de Item",
                "verbose_name_plural": "Doações de Itens",
                "ordering": ["-created_at"],
            },
        ),
    ]
