# Generated by Django 6.0.4 on 2026-06-14 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doacoes", "0005_add_doacaoitem"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DoacaoItem",
        ),
    ]
