# Generated by Django 6.0.4 on 2026-06-25 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacoes', '0006_delete_doacaoitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfertaDoacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_doador', models.CharField(help_text='Nome de quem vai doar', max_length=120)),
                ('telefone', models.CharField(help_text='Telefone/WhatsApp para contato', max_length=20)),
                ('item', models.CharField(help_text='O que deseja doar (ex.: ração, roupa para cães)', max_length=200)),
                ('categoria', models.CharField(choices=[('alimento', 'Alimento / Ração'), ('vestuario', 'Roupa / Cobertor'), ('higiene', 'Higiene / Limpeza'), ('medicamento', 'Medicamento'), ('acessorio', 'Acessório / Brinquedo'), ('outros', 'Outros')], default='outros', help_text='Categoria do item', max_length=20)),
                ('quantidade', models.CharField(blank=True, default='', help_text='Quantidade aproximada (ex.: 3 sacos, 5 peças, 2 kg)', max_length=60)),
                ('observacoes', models.TextField(blank=True, default='', help_text='Detalhes adicionais (estado do item, melhor horário, etc.)')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_contato', 'Em contato'), ('recebida', 'Recebida')], default='pendente', help_text='Andamento do contato com o doador', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Oferta de doação',
                'verbose_name_plural': 'Ofertas de doação',
                'ordering': ['-created_at'],
            },
        ),
    ]
