# Generated by Django 6.0.4 on 2026-06-28 00:38

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doacoes", "0007_ofertadoacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ofertadoacao",
            name="telefone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                help_text="Telefone/WhatsApp para contato", max_length=128, region=None
            ),
        ),
    ]
