# Generated by Django 6.0.4 on 2026-06-13 01:03

import core.uploads
import core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_animal", models.CharField(max_length=30)),
                ("nome_doador", models.CharField(max_length=30)),
                (
                    "telefone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                (
                    "especie",
                    models.CharField(
                        choices=[
                            ("cachorro", "Cachorro"),
                            ("gato", "Gato"),
                            ("outros", "Outros"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "sexo",
                    models.CharField(
                        choices=[("macho", "Macho"), ("femea", "Fêmea")], max_length=10
                    ),
                ),
                (
                    "foto",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=core.uploads.upload_fotos,
                        validators=[core.validators.validate_image_upload],
                    ),
                ),
                ("descricao", models.TextField(blank=True, max_length=500, null=True)),
                ("disponivel", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="AnimalImagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imagem",
                    models.ImageField(
                        upload_to=core.uploads.upload_fotos,
                        validators=[core.validators.validate_image_upload],
                    ),
                ),
                ("ordem", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagens",
                        to="adocao.animal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Foto do animal",
                "verbose_name_plural": "Fotos dos animais",
                "ordering": ["ordem", "id"],
            },
        ),
    ]
