# Generated by Django 6.0.4 on 2026-05-05 20:52

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_doador", models.CharField(max_length=30)),
                (
                    "telefone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, unique=True
                    ),
                ),
                (
                    "especie",
                    models.CharField(
                        choices=[
                            ("cachorro", "Cachorro"),
                            ("gato", "Gato"),
                            ("outros", "Outros"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "sexo",
                    models.CharField(
                        choices=[("macho", "Macho"), ("femea", "Fêmea")], max_length=10
                    ),
                ),
                (
                    "foto",
                    models.ImageField(
                        blank=True, null=True, upload_to="fotos/%Y/%m/%d"
                    ),
                ),
                ("descricao", models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
