# Generated by Django 6.0.4 on 2026-05-13 01:03

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adocao", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="telefone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None
            ),
        ),
    ]
