# Generated by Django 6.0.4 on 2026-06-28 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adocao", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="sexo",
            field=models.CharField(
                choices=[("macho", "Macho"), ("femea", "Fêmea"), ("ambos", "Ambos")],
                max_length=10,
            ),
        ),
    ]
