# Generated by Django 6.0.4 on 2026-06-11 21:52

import core.uploads
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adocao", "0001_animal_disponivel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="foto",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=core.uploads.upload_fotos,
                validators=[core.validators.validate_image_upload],
            ),
        ),
        migrations.AlterField(
            model_name="animalimagem",
            name="imagem",
            field=models.ImageField(
                upload_to=core.uploads.upload_fotos,
                validators=[core.validators.validate_image_upload],
            ),
        ),
    ]
