# Generated by Django 6.0.4 on 2026-05-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adocao", "0003_animal_created_at_animal_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="nome_doador",
            field=models.CharField(max_length=100),
        ),
    ]
