# Generated by Django 6.0.4 on 2026-05-28 00:41

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adocao", "0004_alter_animal_nome_doador"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="nome_doador",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="animal",
            name="telefone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None
            ),
        ),
    ]
