# Generated by Django 6.0.4 on 2026-05-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adocao", "0004_alter_animal_nome_doador"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="nome_animal",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
