# Generated by Django 6.0.4 on 2026-05-28 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adocao", "0005_alter_animal_nome_doador_alter_animal_telefone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="animal",
            name="created_at",
        ),
    ]
