# Generated by Django 6.0.4 on 2026-05-28 00:51

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adocao", "0006_remove_animal_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="telefone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None, unique=True
            ),
        ),
    ]
