# Generated by Django 6.0.4 on 2026-05-28 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adocao", "0007_alter_animal_telefone"),
    ]

    operations = [
        migrations.RenameField(
            model_name="animal",
            old_name="nome",
            new_name="nome_animal",
        ),
        migrations.RemoveField(
            model_name="animal",
            name="criado_em",
        ),
        migrations.RemoveField(
            model_name="animal",
            name="idade",
        ),
        migrations.RemoveField(
            model_name="animal",
            name="updated_at",
        ),
    ]
