# Generated by Django 6.0.4 on 2026-06-03 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adocao', '0008_rename_nome_animal_nome_animal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='fotos/%Y/%m/%d')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='adocao.animal')),
            ],
            options={
                'verbose_name': 'Foto do animal',
                'verbose_name_plural': 'Fotos dos animais',
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
