# Generated by Django 5.0.6 on 2026-06-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adocao", "0009_animalimagem"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="disponivel",
            field=models.BooleanField(
                default="True",
                help_text="Define se um animal está disponível para adoção ou já foi adotado",
            ),
        ),
    ]
