# Generated by Django 6.0.4 on 2026-06-11 21:52

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meta_integration", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metaconnection",
            name="page_access_token",
            field=core.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name="metaoauthstate",
            name="user_access_token",
            field=core.fields.EncryptedTextField(blank=True),
        ),
    ]
