# Generated by Django 6.0.4 on 2026-07-22 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta_integration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaPostLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_id', models.IntegerField(blank=True, null=True)),
                ('animal_nome', models.CharField(blank=True, default='', max_length=60)),
                ('rede', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram')], db_index=True, max_length=20)),
                ('sucesso', models.BooleanField(db_index=True, default=False)),
                ('detalhe', models.TextField(blank=True, default='', help_text='ID do post publicado (sucesso) ou a mensagem de erro (falha).')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Log de publicação (Meta)',
                'verbose_name_plural': 'Logs de publicação (Meta)',
                'ordering': ['-created_at'],
            },
        ),
    ]
