# Generated by Django 6.0.4 on 2026-06-13 01:03

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LarVoluntario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_responsavel",
                    models.CharField(
                        help_text="Nome completo do responsável pelo lar",
                        max_length=200,
                    ),
                ),
                (
                    "telefone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        help_text="Telefone para contato", max_length=128, region=None
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Email para contato (opcional)",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "cidade",
                    models.CharField(
                        help_text="Cidade onde o lar está localizado", max_length=100
                    ),
                ),
                (
                    "tipos_animais",
                    models.CharField(
                        choices=[
                            ("todos", "Todos"),
                            ("caes", "Cães"),
                            ("gatos", "Gatos"),
                            ("caes_gatos", "Cães e Gatos"),
                        ],
                        default="todos",
                        help_text="Tipos de animais aceitos no lar",
                        max_length=20,
                    ),
                ),
                (
                    "capacidade",
                    models.PositiveIntegerField(
                        help_text="Quantidade máxima de animais que pode acolher simultaneamente"
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        help_text="Descreva o ambiente, espaço disponível e experiência com animais"
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        default=True,
                        help_text="Define se o lar está disponível para acolhimento",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Lar Voluntário",
                "verbose_name_plural": "Lares Voluntários",
                "ordering": ["-created_at"],
            },
        ),
    ]
