# Generated by Django 6.0.4 on 2026-06-08 00:14

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Denuncia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Titulo", models.CharField(max_length=30)),
                ("Resumo", models.TextField()),
                (
                    "Gravidade",
                    models.CharField(
                        choices=[
                            ("baixo", "Baixo"),
                            ("medio", "Medio"),
                            ("alta", "Alta"),
                            ("urgente", "Urgente"),
                        ],
                        max_length=50,
                    ),
                ),
                ("nome", models.CharField(blank=True, max_length=40)),
                (
                    "telefone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                (
                    "foto",
                    models.ImageField(
                        blank=True, null=True, upload_to="fotos/%Y/%m/%d"
                    ),
                ),
            ],
        ),
    ]
