# Generated by Django 6.0.4 on 2026-06-13 01:03

import core.uploads
import core.validators
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Denuncia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(help_text="Título da denúncia", max_length=100),
                ),
                (
                    "descricao",
                    models.TextField(help_text="Descrição detalhada da ocorrência"),
                ),
                (
                    "gravidade",
                    models.CharField(
                        choices=[
                            ("baixo", "Baixo"),
                            ("medio", "Médio"),
                            ("alta", "Alta"),
                            ("urgente", "Urgente"),
                        ],
                        help_text="Nível de urgência",
                        max_length=20,
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        blank=True,
                        help_text="Nome do denunciante (opcional)",
                        max_length=100,
                    ),
                ),
                (
                    "telefone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        help_text="Telefone para contato (opcional)",
                        max_length=128,
                        null=True,
                        region=None,
                    ),
                ),
                (
                    "foto",
                    models.ImageField(
                        blank=True,
                        help_text="Foto da ocorrência (opcional)",
                        null=True,
                        upload_to=core.uploads.upload_fotos,
                        validators=[core.validators.validate_image_upload],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("em_analise", "Em análise"),
                            ("resolvida", "Resolvida"),
                        ],
                        default="pendente",
                        help_text="Status de análise da denúncia",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Denúncia",
                "verbose_name_plural": "Denúncias",
                "ordering": ["-created_at"],
            },
        ),
    ]
