# Generated by Django 6.0.4 on 2026-06-11 21:52

import core.uploads
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("denuncias", "0003_telefone_optional"),
    ]

    operations = [
        migrations.AlterField(
            model_name="denuncia",
            name="foto",
            field=models.ImageField(
                blank=True,
                help_text="Foto da ocorrência (opcional)",
                null=True,
                upload_to=core.uploads.upload_fotos,
                validators=[core.validators.validate_image_upload],
            ),
        ),
    ]
