# Generated by Django 6.0.4 on 2026-06-13 01:03

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Voluntario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Nome completo do voluntário", max_length=200
                    ),
                ),
                (
                    "telefone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        help_text="Telefone para contato", max_length=128, region=None
                    ),
                ),
                ("idade", models.IntegerField(help_text="Idade do voluntário")),
                (
                    "motivo",
                    models.TextField(
                        help_text="Motivo pelo qual deseja ser voluntário"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Email para contato (opcional)",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        default=True, help_text="Define se o voluntário está ativo"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Voluntário",
                "verbose_name_plural": "Voluntários",
                "ordering": ["-created_at"],
            },
        ),
    ]
