# Generated by Django 6.0.4 on 2026-06-25 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariado', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voluntario',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Voluntário', 'verbose_name_plural': 'Voluntários'},
        ),
    ]
