# Generated by Django 6.0.4 on 2026-06-13 01:03

import core.uploads
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Publicacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("noticias", "Notícias"),
                            ("resgates", "Resgates"),
                            ("campanhas", "Campanhas"),
                            ("desaparecidos", "Desaparecidos"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("resumo", models.CharField(blank=True, default="", max_length=280)),
                (
                    "foto",
                    models.ImageField(
                        upload_to=core.uploads.upload_noticias,
                        validators=[core.validators.validate_image_upload],
                    ),
                ),
                ("texto", models.TextField()),
                ("ativo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Publicação",
                "verbose_name_plural": "Publicações",
                "ordering": ["-created_at"],
            },
        ),
    ]
