# Generated by Django 6.0.4 on 2026-06-25 21:46

import core.images
import core.uploads
import core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicacaoImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to=core.uploads.upload_noticias, validators=[core.validators.validate_image_upload])),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('publicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='noticias.publicacao')),
            ],
            options={
                'verbose_name': 'Foto da publicação',
                'verbose_name_plural': 'Fotos das publicações',
                'ordering': ['ordem', 'id'],
            },
            bases=(core.images.CompressImageOnSaveMixin, models.Model),
        ),
    ]
