# Generated by Django 6.0.4 on 2026-09-13 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_publicacaoimagem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicacao',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Publicação', 'verbose_name_plural': 'Publicações'},
        ),
    ]
