# Generated by Django 6.0.4 on 2026-06-08 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("noticias", "0003_categoria_desaparecidos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicacao",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("resgates", "Resgates"),
                    ("campanhas", "Campanhas"),
                    ("desaparecidos", "Desaparecidos"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
