# Generated by Django 5.0.6 on 2026-06-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("noticias", "0004_remove_categoria_noticias"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicacao",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("noticias", "Notícias"),
                    ("resgates", "Resgates"),
                    ("campanhas", "Campanhas"),
                    ("desaparecidos", "Desaparecidos"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
