# Generated by Django 6.0.4 on 2026-06-11 21:52

import core.uploads
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("noticias", "0005_alter_publicacao_categoria"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicacao",
            name="foto",
            field=models.ImageField(
                upload_to=core.uploads.upload_noticias,
                validators=[core.validators.validate_image_upload],
            ),
        ),
    ]
