# Generated by Django 6.0.4 on 2026-06-07 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada do produto', null=True)),
                ('tipo', models.CharField(choices=[('humano', 'Vestuário Humano'), ('pet', 'Vestuário para Pet')], help_text='Tipo de vestuário', max_length=10)),
                ('preco', models.DecimalField(decimal_places=2, help_text='Preço do produto', max_digits=10)),
                ('foto', models.ImageField(blank=True, help_text='Foto do produto', null=True, upload_to='produtos/%Y/%m/%d')),
                ('estoque', models.IntegerField(default=0, help_text='Quantidade em estoque')),
                ('ativo', models.BooleanField(default=True, help_text='Define se o produto está disponível para venda')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['-created_at'],
            },
        ),
    ]
