# Generated by Django 6.0.4 on 2026-06-03 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='produtos/%Y/%m/%d')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='vendas.produto')),
            ],
            options={
                'verbose_name': 'Foto do produto',
                'verbose_name_plural': 'Fotos dos produtos',
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
