# Generated by Django 6.0.4 on 2026-06-11 21:52

import core.uploads
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendas", "0002_produtoimagem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="foto",
            field=models.ImageField(
                blank=True,
                help_text="Foto do produto",
                null=True,
                upload_to=core.uploads.upload_produtos,
                validators=[core.validators.validate_image_upload],
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="tipo",
            field=models.CharField(
                choices=[("humano", "Para pessoas"), ("pet", "Para pets")],
                help_text="Tipo de vestuário",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="produtoimagem",
            name="imagem",
            field=models.ImageField(
                upload_to=core.uploads.upload_produtos,
                validators=[core.validators.validate_image_upload],
            ),
        ),
    ]
