# Generated by Django 6.0.4 on 2026-06-13 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContatoAcapra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("whatsapp_castracoes", models.CharField(blank=True, max_length=20)),
                ("whatsapp_doacoes", models.CharField(blank=True, max_length=20)),
                ("whatsapp_financeiro", models.CharField(blank=True, max_length=20)),
                ("instagram", models.URLField(blank=True, max_length=255)),
                ("facebook", models.URLField(blank=True, max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
            ],
            options={
                "verbose_name": "Contato ACAPRA",
            },
        ),
    ]
