# Generated by Django 6.0.4 on 2026-06-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contato", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contatoacapra",
            name="emaildoacoes",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="contatoacapra",
            name="emailfinanceiro",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
