# Generated by Django 6.0.4 on 2026-06-13 03:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('criado', 'Criado'), ('editado', 'Editado'), ('excluido', 'Excluído')], max_length=10)),
                ('modelo', models.CharField(help_text='Entidade afetada (ex.: DadosPix)', max_length=100)),
                ('objeto_id', models.CharField(blank=True, help_text='PK do registro afetado', max_length=64)),
                ('descricao', models.CharField(blank=True, help_text='Resumo legível do registro', max_length=255)),
                ('alteracoes', models.JSONField(blank=True, null=True)),
                ('usuario_email', models.CharField(blank=True, max_length=254)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acoes_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de auditoria',
                'verbose_name_plural': 'Registros de auditoria',
                'ordering': ['-data_hora'],
                'indexes': [models.Index(fields=['modelo', 'objeto_id'], name='auditoria_r_modelo_e0db67_idx'), models.Index(fields=['-data_hora'], name='auditoria_r_data_ho_9aa85c_idx')],
            },
        ),
    ]
